### PR TITLE
WIP: Add Last-Modified and ETag headers

### LINKED ISSUE #26: Responses have no Last-Modified and ETag headers
In order to support HTTP cache-revalidation, we need to ensure that there is a Last-Modified and an ETag header on the response.

### PR DESCRIPTION
**Pull request by DieterHolvoet**
Fixes #26. WIP since I still need to inject the dependency, but still trying out stuff so far.

### CODE REVIEW

**Comment by RobinHoutevelts** [comment]
You'll need to remove this piece of code. We added it because at one point we were displaying blank pages but didn't know why.

https://github.com/wieni/wmpage_cache/blob/fd699f101c6d625173596da6c5135bd8bdc5a770/src/EventSubscriber/CacheSubscriber.php#L101-L103

**Comment by DieterHolvoet** [comment]
@RobinHoutevelts is that related to this PR or just something you noticed randomly?

**Comment by RobinHoutevelts** [comment]
@DieterHolvoet related to this PR.

We [already call `$response->isNotModified($request);`](https://github.com/wieni/wmpage_cache/blob/1.0.0-alpha3/src/EventSubscriber/CacheSubscriber.php#L95)
Before, it never really did anything. But with your changes it will.

Symfony will check if the cached Response is deemed modified or not.
If it isn't, it will call [`::setNotModified()`](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpFoundation/Response.php#L1077-L1088) on the response, which [sets the content to `null`](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpFoundation/Response.php#L1080).
So we end up in that `if (empty($response->getContent()))`- block and return early.

Here is the entire code again to save you a click:

https://github.com/wieni/wmpage_cache/blob/fd699f101c6d625173596da6c5135bd8bdc5a770/src/EventSubscriber/CacheSubscriber.php#L91-L106

**Comment by RobinHoutevelts** [comment]
Cool! Nice work. Let me know if this works.
Can I backport this into wmcontroller?

If so, can you "squash and merge" when you decide to merge?
Makes it easier for me to cherry-pick 😇

**Review by RobinHoutevelts — APPROVED** [review]

**Pull request merged**
